info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /user/getUserList:
    get:
      responses:
        "200":
          description: code":"users"}
          schema:
            type: string
      summary: 查询所有用户
      tags:
      - 用户模块
  /user/register:
    post:
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      - description: 确认密码
        in: query
        name: confirmPassword
        type: string
      - description: 邮件
        in: query
        name: email
        type: string
      - description: 电话号码
        in: query
        name: telephone
        type: string
      responses:
        "200":
          description: code":"users"}
          schema:
            type: string
      summary: 新增用户
      tags:
      - 用户模块
  /user/updateUser:
    post:
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 旧密码
        in: query
        name: oldPassword
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      - description: 确认密码
        in: query
        name: confirmPassword
        type: string
      - description: 邮件
        in: query
        name: email
        type: string
      - description: 电话号码
        in: query
        name: telephone
        type: string
      responses:
        "200":
          description: code":"users"}
          schema:
            type: string
      summary: 修改用户
      tags:
      - 用户模块
swagger: "2.0"
